// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticeAPI.Data;

namespace PracticeAPI.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20211117155409_NewMigration")]
    partial class NewMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PracticeAPI.Models.ChildA", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentAId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Profesion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentAId");

                    b.ToTable("ChildAs");
                });

            modelBuilder.Entity("PracticeAPI.Models.ChildB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentBId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Profesion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentBId");

                    b.ToTable("ChildBs");
                });

            modelBuilder.Entity("PracticeAPI.Models.ParentA", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profesion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ParentAs");
                });

            modelBuilder.Entity("PracticeAPI.Models.ParentB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profesion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ParentBs");
                });

            modelBuilder.Entity("PracticeAPI.Models.PrivateClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PrivateClients");
                });

            modelBuilder.Entity("PracticeAPI.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PracticeAPI.Models.PublicClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PublicClients");
                });

            modelBuilder.Entity("PracticeAPI.Models.ThingA", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChildAId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Num")
                        .HasColumnType("int");

                    b.Property<string>("Word")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChildAId");

                    b.ToTable("ThingAs");
                });

            modelBuilder.Entity("PracticeAPI.Models.ThingB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChildBId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Num")
                        .HasColumnType("int");

                    b.Property<string>("Word")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChildBId");

                    b.ToTable("ThingBs");
                });

            modelBuilder.Entity("PracticeAPI.Models.ChildA", b =>
                {
                    b.HasOne("PracticeAPI.Models.ParentA", null)
                        .WithMany("Childs")
                        .HasForeignKey("ParentAId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PracticeAPI.Models.ChildB", b =>
                {
                    b.HasOne("PracticeAPI.Models.ParentB", null)
                        .WithMany("Childs")
                        .HasForeignKey("ParentBId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PracticeAPI.Models.ThingA", b =>
                {
                    b.HasOne("PracticeAPI.Models.ChildA", null)
                        .WithMany("Things")
                        .HasForeignKey("ChildAId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PracticeAPI.Models.ThingB", b =>
                {
                    b.HasOne("PracticeAPI.Models.ChildB", null)
                        .WithMany("Things")
                        .HasForeignKey("ChildBId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PracticeAPI.Models.ChildA", b =>
                {
                    b.Navigation("Things");
                });

            modelBuilder.Entity("PracticeAPI.Models.ChildB", b =>
                {
                    b.Navigation("Things");
                });

            modelBuilder.Entity("PracticeAPI.Models.ParentA", b =>
                {
                    b.Navigation("Childs");
                });

            modelBuilder.Entity("PracticeAPI.Models.ParentB", b =>
                {
                    b.Navigation("Childs");
                });
#pragma warning restore 612, 618
        }
    }
}
